//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ExpenseManager.CoreFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class expensemanagerportaldbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new expensemanagerportaldbEntities object using the connection string found in the 'expensemanagerportaldbEntities' section of the application configuration file.
        /// </summary>
        public expensemanagerportaldbEntities() : base("name=expensemanagerportaldbEntities", "expensemanagerportaldbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new expensemanagerportaldbEntities object.
        /// </summary>
        public expensemanagerportaldbEntities(string connectionString) : base(connectionString, "expensemanagerportaldbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new expensemanagerportaldbEntities object.
        /// </summary>
        public expensemanagerportaldbEntities(EntityConnection connection) : base(connection, "expensemanagerportaldbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_applications> my_aspnet_applications
        {
            get
            {
                if ((_my_aspnet_applications == null))
                {
                    _my_aspnet_applications = base.CreateObjectSet<my_aspnet_applications>("my_aspnet_applications");
                }
                return _my_aspnet_applications;
            }
        }
        private ObjectSet<my_aspnet_applications> _my_aspnet_applications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_membership> my_aspnet_membership
        {
            get
            {
                if ((_my_aspnet_membership == null))
                {
                    _my_aspnet_membership = base.CreateObjectSet<my_aspnet_membership>("my_aspnet_membership");
                }
                return _my_aspnet_membership;
            }
        }
        private ObjectSet<my_aspnet_membership> _my_aspnet_membership;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_profiles> my_aspnet_profiles
        {
            get
            {
                if ((_my_aspnet_profiles == null))
                {
                    _my_aspnet_profiles = base.CreateObjectSet<my_aspnet_profiles>("my_aspnet_profiles");
                }
                return _my_aspnet_profiles;
            }
        }
        private ObjectSet<my_aspnet_profiles> _my_aspnet_profiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_roles> my_aspnet_roles
        {
            get
            {
                if ((_my_aspnet_roles == null))
                {
                    _my_aspnet_roles = base.CreateObjectSet<my_aspnet_roles>("my_aspnet_roles");
                }
                return _my_aspnet_roles;
            }
        }
        private ObjectSet<my_aspnet_roles> _my_aspnet_roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup
        {
            get
            {
                if ((_my_aspnet_sessioncleanup == null))
                {
                    _my_aspnet_sessioncleanup = base.CreateObjectSet<my_aspnet_sessioncleanup>("my_aspnet_sessioncleanup");
                }
                return _my_aspnet_sessioncleanup;
            }
        }
        private ObjectSet<my_aspnet_sessioncleanup> _my_aspnet_sessioncleanup;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_sessions> my_aspnet_sessions
        {
            get
            {
                if ((_my_aspnet_sessions == null))
                {
                    _my_aspnet_sessions = base.CreateObjectSet<my_aspnet_sessions>("my_aspnet_sessions");
                }
                return _my_aspnet_sessions;
            }
        }
        private ObjectSet<my_aspnet_sessions> _my_aspnet_sessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_users> my_aspnet_users
        {
            get
            {
                if ((_my_aspnet_users == null))
                {
                    _my_aspnet_users = base.CreateObjectSet<my_aspnet_users>("my_aspnet_users");
                }
                return _my_aspnet_users;
            }
        }
        private ObjectSet<my_aspnet_users> _my_aspnet_users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<my_aspnet_usersinroles> my_aspnet_usersinroles
        {
            get
            {
                if ((_my_aspnet_usersinroles == null))
                {
                    _my_aspnet_usersinroles = base.CreateObjectSet<my_aspnet_usersinroles>("my_aspnet_usersinroles");
                }
                return _my_aspnet_usersinroles;
            }
        }
        private ObjectSet<my_aspnet_usersinroles> _my_aspnet_usersinroles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<portaluser> portalusers
        {
            get
            {
                if ((_portalusers == null))
                {
                    _portalusers = base.CreateObjectSet<portaluser>("portalusers");
                }
                return _portalusers;
            }
        }
        private ObjectSet<portaluser> _portalusers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sitemap> sitemaps
        {
            get
            {
                if ((_sitemaps == null))
                {
                    _sitemaps = base.CreateObjectSet<sitemap>("sitemaps");
                }
                return _sitemaps;
            }
        }
        private ObjectSet<sitemap> _sitemaps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_applications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_applications(my_aspnet_applications my_aspnet_applications)
        {
            base.AddObject("my_aspnet_applications", my_aspnet_applications);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_membership EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_membership(my_aspnet_membership my_aspnet_membership)
        {
            base.AddObject("my_aspnet_membership", my_aspnet_membership);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_profiles(my_aspnet_profiles my_aspnet_profiles)
        {
            base.AddObject("my_aspnet_profiles", my_aspnet_profiles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_roles(my_aspnet_roles my_aspnet_roles)
        {
            base.AddObject("my_aspnet_roles", my_aspnet_roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_sessioncleanup EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_sessioncleanup(my_aspnet_sessioncleanup my_aspnet_sessioncleanup)
        {
            base.AddObject("my_aspnet_sessioncleanup", my_aspnet_sessioncleanup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_sessions(my_aspnet_sessions my_aspnet_sessions)
        {
            base.AddObject("my_aspnet_sessions", my_aspnet_sessions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_users(my_aspnet_users my_aspnet_users)
        {
            base.AddObject("my_aspnet_users", my_aspnet_users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the my_aspnet_usersinroles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomy_aspnet_usersinroles(my_aspnet_usersinroles my_aspnet_usersinroles)
        {
            base.AddObject("my_aspnet_usersinroles", my_aspnet_usersinroles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the portalusers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToportalusers(portaluser portaluser)
        {
            base.AddObject("portalusers", portaluser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sitemaps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTositemaps(sitemap sitemap)
        {
            base.AddObject("sitemaps", sitemap);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_applications")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_applications : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_applications object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static my_aspnet_applications Createmy_aspnet_applications(global::System.Int32 id)
        {
            my_aspnet_applications my_aspnet_applications = new my_aspnet_applications();
            my_aspnet_applications.id = id;
            return my_aspnet_applications;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_membership")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_membership : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_membership object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static my_aspnet_membership Createmy_aspnet_membership(global::System.Int32 userId, global::System.String password)
        {
            my_aspnet_membership my_aspnet_membership = new my_aspnet_membership();
            my_aspnet_membership.userId = userId;
            my_aspnet_membership.Password = password;
            return my_aspnet_membership;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int32 _userId;
        partial void OnuserIdChanging(global::System.Int32 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordKey
        {
            get
            {
                return _PasswordKey;
            }
            set
            {
                OnPasswordKeyChanging(value);
                ReportPropertyChanging("PasswordKey");
                _PasswordKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordKey");
                OnPasswordKeyChanged();
            }
        }
        private global::System.String _PasswordKey;
        partial void OnPasswordKeyChanging(global::System.String value);
        partial void OnPasswordKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> PasswordFormat
        {
            get
            {
                return _PasswordFormat;
            }
            set
            {
                OnPasswordFormatChanging(value);
                ReportPropertyChanging("PasswordFormat");
                _PasswordFormat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordFormat");
                OnPasswordFormatChanged();
            }
        }
        private Nullable<global::System.SByte> _PasswordFormat;
        partial void OnPasswordFormatChanging(Nullable<global::System.SByte> value);
        partial void OnPasswordFormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordQuestion
        {
            get
            {
                return _PasswordQuestion;
            }
            set
            {
                OnPasswordQuestionChanging(value);
                ReportPropertyChanging("PasswordQuestion");
                _PasswordQuestion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordQuestion");
                OnPasswordQuestionChanged();
            }
        }
        private global::System.String _PasswordQuestion;
        partial void OnPasswordQuestionChanging(global::System.String value);
        partial void OnPasswordQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordAnswer
        {
            get
            {
                return _PasswordAnswer;
            }
            set
            {
                OnPasswordAnswerChanging(value);
                ReportPropertyChanging("PasswordAnswer");
                _PasswordAnswer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordAnswer");
                OnPasswordAnswerChanged();
            }
        }
        private global::System.String _PasswordAnswer;
        partial void OnPasswordAnswerChanging(global::System.String value);
        partial void OnPasswordAnswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsApproved
        {
            get
            {
                return _IsApproved;
            }
            set
            {
                OnIsApprovedChanging(value);
                ReportPropertyChanging("IsApproved");
                _IsApproved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsApproved");
                OnIsApprovedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsApproved;
        partial void OnIsApprovedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastActivityDate;
        partial void OnLastActivityDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastActivityDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastPasswordChangedDate
        {
            get
            {
                return _LastPasswordChangedDate;
            }
            set
            {
                OnLastPasswordChangedDateChanging(value);
                ReportPropertyChanging("LastPasswordChangedDate");
                _LastPasswordChangedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastPasswordChangedDate");
                OnLastPasswordChangedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastPasswordChangedDate;
        partial void OnLastPasswordChangedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastPasswordChangedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsLockedOut
        {
            get
            {
                return _IsLockedOut;
            }
            set
            {
                OnIsLockedOutChanging(value);
                ReportPropertyChanging("IsLockedOut");
                _IsLockedOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLockedOut");
                OnIsLockedOutChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsLockedOut;
        partial void OnIsLockedOutChanging(Nullable<global::System.Boolean> value);
        partial void OnIsLockedOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLockedOutDate
        {
            get
            {
                return _LastLockedOutDate;
            }
            set
            {
                OnLastLockedOutDateChanging(value);
                ReportPropertyChanging("LastLockedOutDate");
                _LastLockedOutDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLockedOutDate");
                OnLastLockedOutDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLockedOutDate;
        partial void OnLastLockedOutDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLockedOutDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FailedPasswordAttemptCount
        {
            get
            {
                return _FailedPasswordAttemptCount;
            }
            set
            {
                OnFailedPasswordAttemptCountChanging(value);
                ReportPropertyChanging("FailedPasswordAttemptCount");
                _FailedPasswordAttemptCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedPasswordAttemptCount");
                OnFailedPasswordAttemptCountChanged();
            }
        }
        private Nullable<global::System.Int64> _FailedPasswordAttemptCount;
        partial void OnFailedPasswordAttemptCountChanging(Nullable<global::System.Int64> value);
        partial void OnFailedPasswordAttemptCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FailedPasswordAttemptWindowStart
        {
            get
            {
                return _FailedPasswordAttemptWindowStart;
            }
            set
            {
                OnFailedPasswordAttemptWindowStartChanging(value);
                ReportPropertyChanging("FailedPasswordAttemptWindowStart");
                _FailedPasswordAttemptWindowStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedPasswordAttemptWindowStart");
                OnFailedPasswordAttemptWindowStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _FailedPasswordAttemptWindowStart;
        partial void OnFailedPasswordAttemptWindowStartChanging(Nullable<global::System.DateTime> value);
        partial void OnFailedPasswordAttemptWindowStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FailedPasswordAnswerAttemptCount
        {
            get
            {
                return _FailedPasswordAnswerAttemptCount;
            }
            set
            {
                OnFailedPasswordAnswerAttemptCountChanging(value);
                ReportPropertyChanging("FailedPasswordAnswerAttemptCount");
                _FailedPasswordAnswerAttemptCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedPasswordAnswerAttemptCount");
                OnFailedPasswordAnswerAttemptCountChanged();
            }
        }
        private Nullable<global::System.Int64> _FailedPasswordAnswerAttemptCount;
        partial void OnFailedPasswordAnswerAttemptCountChanging(Nullable<global::System.Int64> value);
        partial void OnFailedPasswordAnswerAttemptCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FailedPasswordAnswerAttemptWindowStart
        {
            get
            {
                return _FailedPasswordAnswerAttemptWindowStart;
            }
            set
            {
                OnFailedPasswordAnswerAttemptWindowStartChanging(value);
                ReportPropertyChanging("FailedPasswordAnswerAttemptWindowStart");
                _FailedPasswordAnswerAttemptWindowStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
                OnFailedPasswordAnswerAttemptWindowStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _FailedPasswordAnswerAttemptWindowStart;
        partial void OnFailedPasswordAnswerAttemptWindowStartChanging(Nullable<global::System.DateTime> value);
        partial void OnFailedPasswordAnswerAttemptWindowStartChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_profiles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_profiles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_profiles object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="lastUpdatedDate">Initial value of the lastUpdatedDate property.</param>
        public static my_aspnet_profiles Createmy_aspnet_profiles(global::System.Int32 userId, global::System.DateTime lastUpdatedDate)
        {
            my_aspnet_profiles my_aspnet_profiles = new my_aspnet_profiles();
            my_aspnet_profiles.userId = userId;
            my_aspnet_profiles.lastUpdatedDate = lastUpdatedDate;
            return my_aspnet_profiles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int32 _userId;
        partial void OnuserIdChanging(global::System.Int32 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String valueindex
        {
            get
            {
                return _valueindex;
            }
            set
            {
                OnvalueindexChanging(value);
                ReportPropertyChanging("valueindex");
                _valueindex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("valueindex");
                OnvalueindexChanged();
            }
        }
        private global::System.String _valueindex;
        partial void OnvalueindexChanging(global::System.String value);
        partial void OnvalueindexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stringdata
        {
            get
            {
                return _stringdata;
            }
            set
            {
                OnstringdataChanging(value);
                ReportPropertyChanging("stringdata");
                _stringdata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stringdata");
                OnstringdataChanged();
            }
        }
        private global::System.String _stringdata;
        partial void OnstringdataChanging(global::System.String value);
        partial void OnstringdataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] binarydata
        {
            get
            {
                return StructuralObject.GetValidValue(_binarydata);
            }
            set
            {
                OnbinarydataChanging(value);
                ReportPropertyChanging("binarydata");
                _binarydata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("binarydata");
                OnbinarydataChanged();
            }
        }
        private global::System.Byte[] _binarydata;
        partial void OnbinarydataChanging(global::System.Byte[] value);
        partial void OnbinarydataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastUpdatedDate
        {
            get
            {
                return _lastUpdatedDate;
            }
            set
            {
                OnlastUpdatedDateChanging(value);
                ReportPropertyChanging("lastUpdatedDate");
                _lastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastUpdatedDate");
                OnlastUpdatedDateChanged();
            }
        }
        private global::System.DateTime _lastUpdatedDate;
        partial void OnlastUpdatedDateChanging(global::System.DateTime value);
        partial void OnlastUpdatedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_roles object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="applicationId">Initial value of the applicationId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static my_aspnet_roles Createmy_aspnet_roles(global::System.Int32 id, global::System.Int32 applicationId, global::System.String name)
        {
            my_aspnet_roles my_aspnet_roles = new my_aspnet_roles();
            my_aspnet_roles.id = id;
            my_aspnet_roles.applicationId = applicationId;
            my_aspnet_roles.name = name;
            return my_aspnet_roles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 applicationId
        {
            get
            {
                return _applicationId;
            }
            set
            {
                OnapplicationIdChanging(value);
                ReportPropertyChanging("applicationId");
                _applicationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("applicationId");
                OnapplicationIdChanged();
            }
        }
        private global::System.Int32 _applicationId;
        partial void OnapplicationIdChanging(global::System.Int32 value);
        partial void OnapplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_sessioncleanup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_sessioncleanup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_sessioncleanup object.
        /// </summary>
        /// <param name="lastRun">Initial value of the LastRun property.</param>
        /// <param name="intervalMinutes">Initial value of the IntervalMinutes property.</param>
        /// <param name="applicationId">Initial value of the ApplicationId property.</param>
        public static my_aspnet_sessioncleanup Createmy_aspnet_sessioncleanup(global::System.DateTime lastRun, global::System.Int32 intervalMinutes, global::System.Int32 applicationId)
        {
            my_aspnet_sessioncleanup my_aspnet_sessioncleanup = new my_aspnet_sessioncleanup();
            my_aspnet_sessioncleanup.LastRun = lastRun;
            my_aspnet_sessioncleanup.IntervalMinutes = intervalMinutes;
            my_aspnet_sessioncleanup.ApplicationId = applicationId;
            return my_aspnet_sessioncleanup;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastRun
        {
            get
            {
                return _LastRun;
            }
            set
            {
                OnLastRunChanging(value);
                ReportPropertyChanging("LastRun");
                _LastRun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastRun");
                OnLastRunChanged();
            }
        }
        private global::System.DateTime _LastRun;
        partial void OnLastRunChanging(global::System.DateTime value);
        partial void OnLastRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IntervalMinutes
        {
            get
            {
                return _IntervalMinutes;
            }
            set
            {
                OnIntervalMinutesChanging(value);
                ReportPropertyChanging("IntervalMinutes");
                _IntervalMinutes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IntervalMinutes");
                OnIntervalMinutesChanged();
            }
        }
        private global::System.Int32 _IntervalMinutes;
        partial void OnIntervalMinutesChanging(global::System.Int32 value);
        partial void OnIntervalMinutesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                if (_ApplicationId != value)
                {
                    OnApplicationIdChanging(value);
                    ReportPropertyChanging("ApplicationId");
                    _ApplicationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ApplicationId");
                    OnApplicationIdChanged();
                }
            }
        }
        private global::System.Int32 _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Int32 value);
        partial void OnApplicationIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_sessions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_sessions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_sessions object.
        /// </summary>
        /// <param name="sessionId">Initial value of the SessionId property.</param>
        /// <param name="applicationId">Initial value of the ApplicationId property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="expires">Initial value of the Expires property.</param>
        /// <param name="lockDate">Initial value of the LockDate property.</param>
        /// <param name="lockId">Initial value of the LockId property.</param>
        /// <param name="timeout">Initial value of the Timeout property.</param>
        /// <param name="locked">Initial value of the Locked property.</param>
        /// <param name="flags">Initial value of the Flags property.</param>
        public static my_aspnet_sessions Createmy_aspnet_sessions(global::System.String sessionId, global::System.Int32 applicationId, global::System.DateTime created, global::System.DateTime expires, global::System.DateTime lockDate, global::System.Int32 lockId, global::System.Int32 timeout, global::System.Boolean locked, global::System.Int32 flags)
        {
            my_aspnet_sessions my_aspnet_sessions = new my_aspnet_sessions();
            my_aspnet_sessions.SessionId = sessionId;
            my_aspnet_sessions.ApplicationId = applicationId;
            my_aspnet_sessions.Created = created;
            my_aspnet_sessions.Expires = expires;
            my_aspnet_sessions.LockDate = lockDate;
            my_aspnet_sessions.LockId = lockId;
            my_aspnet_sessions.Timeout = timeout;
            my_aspnet_sessions.Locked = locked;
            my_aspnet_sessions.Flags = flags;
            return my_aspnet_sessions;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                if (_SessionId != value)
                {
                    OnSessionIdChanging(value);
                    ReportPropertyChanging("SessionId");
                    _SessionId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SessionId");
                    OnSessionIdChanged();
                }
            }
        }
        private global::System.String _SessionId;
        partial void OnSessionIdChanging(global::System.String value);
        partial void OnSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                if (_ApplicationId != value)
                {
                    OnApplicationIdChanging(value);
                    ReportPropertyChanging("ApplicationId");
                    _ApplicationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ApplicationId");
                    OnApplicationIdChanged();
                }
            }
        }
        private global::System.Int32 _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Int32 value);
        partial void OnApplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Expires
        {
            get
            {
                return _Expires;
            }
            set
            {
                OnExpiresChanging(value);
                ReportPropertyChanging("Expires");
                _Expires = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expires");
                OnExpiresChanged();
            }
        }
        private global::System.DateTime _Expires;
        partial void OnExpiresChanging(global::System.DateTime value);
        partial void OnExpiresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LockDate
        {
            get
            {
                return _LockDate;
            }
            set
            {
                OnLockDateChanging(value);
                ReportPropertyChanging("LockDate");
                _LockDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LockDate");
                OnLockDateChanged();
            }
        }
        private global::System.DateTime _LockDate;
        partial void OnLockDateChanging(global::System.DateTime value);
        partial void OnLockDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LockId
        {
            get
            {
                return _LockId;
            }
            set
            {
                OnLockIdChanging(value);
                ReportPropertyChanging("LockId");
                _LockId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LockId");
                OnLockIdChanged();
            }
        }
        private global::System.Int32 _LockId;
        partial void OnLockIdChanging(global::System.Int32 value);
        partial void OnLockIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Timeout
        {
            get
            {
                return _Timeout;
            }
            set
            {
                OnTimeoutChanging(value);
                ReportPropertyChanging("Timeout");
                _Timeout = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timeout");
                OnTimeoutChanged();
            }
        }
        private global::System.Int32 _Timeout;
        partial void OnTimeoutChanging(global::System.Int32 value);
        partial void OnTimeoutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Locked
        {
            get
            {
                return _Locked;
            }
            set
            {
                OnLockedChanging(value);
                ReportPropertyChanging("Locked");
                _Locked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Locked");
                OnLockedChanged();
            }
        }
        private global::System.Boolean _Locked;
        partial void OnLockedChanging(global::System.Boolean value);
        partial void OnLockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] SessionItems
        {
            get
            {
                return StructuralObject.GetValidValue(_SessionItems);
            }
            set
            {
                OnSessionItemsChanging(value);
                ReportPropertyChanging("SessionItems");
                _SessionItems = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SessionItems");
                OnSessionItemsChanged();
            }
        }
        private global::System.Byte[] _SessionItems;
        partial void OnSessionItemsChanging(global::System.Byte[] value);
        partial void OnSessionItemsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Flags
        {
            get
            {
                return _Flags;
            }
            set
            {
                OnFlagsChanging(value);
                ReportPropertyChanging("Flags");
                _Flags = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flags");
                OnFlagsChanged();
            }
        }
        private global::System.Int32 _Flags;
        partial void OnFlagsChanging(global::System.Int32 value);
        partial void OnFlagsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_users object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="applicationId">Initial value of the applicationId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="isAnonymous">Initial value of the isAnonymous property.</param>
        public static my_aspnet_users Createmy_aspnet_users(global::System.Int32 id, global::System.Int32 applicationId, global::System.String name, global::System.Boolean isAnonymous)
        {
            my_aspnet_users my_aspnet_users = new my_aspnet_users();
            my_aspnet_users.id = id;
            my_aspnet_users.applicationId = applicationId;
            my_aspnet_users.name = name;
            my_aspnet_users.isAnonymous = isAnonymous;
            return my_aspnet_users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 applicationId
        {
            get
            {
                return _applicationId;
            }
            set
            {
                OnapplicationIdChanging(value);
                ReportPropertyChanging("applicationId");
                _applicationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("applicationId");
                OnapplicationIdChanged();
            }
        }
        private global::System.Int32 _applicationId;
        partial void OnapplicationIdChanging(global::System.Int32 value);
        partial void OnapplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isAnonymous
        {
            get
            {
                return _isAnonymous;
            }
            set
            {
                OnisAnonymousChanging(value);
                ReportPropertyChanging("isAnonymous");
                _isAnonymous = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAnonymous");
                OnisAnonymousChanged();
            }
        }
        private global::System.Boolean _isAnonymous;
        partial void OnisAnonymousChanging(global::System.Boolean value);
        partial void OnisAnonymousChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastActivityDate
        {
            get
            {
                return _lastActivityDate;
            }
            set
            {
                OnlastActivityDateChanging(value);
                ReportPropertyChanging("lastActivityDate");
                _lastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastActivityDate");
                OnlastActivityDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastActivityDate;
        partial void OnlastActivityDateChanging(Nullable<global::System.DateTime> value);
        partial void OnlastActivityDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="my_aspnet_usersinroles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class my_aspnet_usersinroles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new my_aspnet_usersinroles object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="roleId">Initial value of the roleId property.</param>
        public static my_aspnet_usersinroles Createmy_aspnet_usersinroles(global::System.Int32 userId, global::System.Int32 roleId)
        {
            my_aspnet_usersinroles my_aspnet_usersinroles = new my_aspnet_usersinroles();
            my_aspnet_usersinroles.userId = userId;
            my_aspnet_usersinroles.roleId = roleId;
            return my_aspnet_usersinroles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int32 _userId;
        partial void OnuserIdChanging(global::System.Int32 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleId
        {
            get
            {
                return _roleId;
            }
            set
            {
                if (_roleId != value)
                {
                    OnroleIdChanging(value);
                    ReportPropertyChanging("roleId");
                    _roleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("roleId");
                    OnroleIdChanged();
                }
            }
        }
        private global::System.Int32 _roleId;
        partial void OnroleIdChanging(global::System.Int32 value);
        partial void OnroleIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="portaluser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class portaluser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new portaluser object.
        /// </summary>
        /// <param name="portalUserId">Initial value of the PortalUserId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="sexId">Initial value of the SexId property.</param>
        /// <param name="dateRegistered">Initial value of the DateRegistered property.</param>
        /// <param name="timeRegistered">Initial value of the TimeRegistered property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static portaluser Createportaluser(global::System.Int64 portalUserId, global::System.Int32 userId, global::System.String firstName, global::System.String lastName, global::System.Int32 sexId, global::System.String dateRegistered, global::System.String timeRegistered, global::System.String userName, global::System.Boolean status)
        {
            portaluser portaluser = new portaluser();
            portaluser.PortalUserId = portalUserId;
            portaluser.UserId = userId;
            portaluser.FirstName = firstName;
            portaluser.LastName = lastName;
            portaluser.SexId = sexId;
            portaluser.DateRegistered = dateRegistered;
            portaluser.TimeRegistered = timeRegistered;
            portaluser.UserName = userName;
            portaluser.Status = status;
            return portaluser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PortalUserId
        {
            get
            {
                return _PortalUserId;
            }
            set
            {
                if (_PortalUserId != value)
                {
                    OnPortalUserIdChanging(value);
                    ReportPropertyChanging("PortalUserId");
                    _PortalUserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PortalUserId");
                    OnPortalUserIdChanged();
                }
            }
        }
        private global::System.Int64 _PortalUserId;
        partial void OnPortalUserIdChanging(global::System.Int64 value);
        partial void OnPortalUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherName
        {
            get
            {
                return _OtherName;
            }
            set
            {
                OnOtherNameChanging(value);
                ReportPropertyChanging("OtherName");
                _OtherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherName");
                OnOtherNameChanged();
            }
        }
        private global::System.String _OtherName;
        partial void OnOtherNameChanging(global::System.String value);
        partial void OnOtherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SexId
        {
            get
            {
                return _SexId;
            }
            set
            {
                OnSexIdChanging(value);
                ReportPropertyChanging("SexId");
                _SexId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SexId");
                OnSexIdChanged();
            }
        }
        private global::System.Int32 _SexId;
        partial void OnSexIdChanging(global::System.Int32 value);
        partial void OnSexIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileNumber
        {
            get
            {
                return _MobileNumber;
            }
            set
            {
                OnMobileNumberChanging(value);
                ReportPropertyChanging("MobileNumber");
                _MobileNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileNumber");
                OnMobileNumberChanged();
            }
        }
        private global::System.String _MobileNumber;
        partial void OnMobileNumberChanging(global::System.String value);
        partial void OnMobileNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateRegistered
        {
            get
            {
                return _DateRegistered;
            }
            set
            {
                OnDateRegisteredChanging(value);
                ReportPropertyChanging("DateRegistered");
                _DateRegistered = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateRegistered");
                OnDateRegisteredChanged();
            }
        }
        private global::System.String _DateRegistered;
        partial void OnDateRegisteredChanging(global::System.String value);
        partial void OnDateRegisteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TimeRegistered
        {
            get
            {
                return _TimeRegistered;
            }
            set
            {
                OnTimeRegisteredChanging(value);
                ReportPropertyChanging("TimeRegistered");
                _TimeRegistered = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TimeRegistered");
                OnTimeRegisteredChanged();
            }
        }
        private global::System.String _TimeRegistered;
        partial void OnTimeRegisteredChanging(global::System.String value);
        partial void OnTimeRegisteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Boolean _Status;
        partial void OnStatusChanging(global::System.Boolean value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TestProviderId
        {
            get
            {
                return _TestProviderId;
            }
            set
            {
                OnTestProviderIdChanging(value);
                ReportPropertyChanging("TestProviderId");
                _TestProviderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestProviderId");
                OnTestProviderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TestProviderId;
        partial void OnTestProviderIdChanging(Nullable<global::System.Int32> value);
        partial void OnTestProviderIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="expensemanagerportaldbModel", Name="sitemap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sitemap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sitemap object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="tabOrder">Initial value of the TabOrder property.</param>
        public static sitemap Createsitemap(global::System.Int32 id, global::System.String title, global::System.Int32 tabOrder)
        {
            sitemap sitemap = new sitemap();
            sitemap.ID = id;
            sitemap.Title = title;
            sitemap.TabOrder = tabOrder;
            return sitemap;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Roles
        {
            get
            {
                return _Roles;
            }
            set
            {
                OnRolesChanging(value);
                ReportPropertyChanging("Roles");
                _Roles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Roles");
                OnRolesChanged();
            }
        }
        private global::System.String _Roles;
        partial void OnRolesChanging(global::System.String value);
        partial void OnRolesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Parent
        {
            get
            {
                return _Parent;
            }
            set
            {
                OnParentChanging(value);
                ReportPropertyChanging("Parent");
                _Parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parent");
                OnParentChanged();
            }
        }
        private Nullable<global::System.Int32> _Parent;
        partial void OnParentChanging(Nullable<global::System.Int32> value);
        partial void OnParentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TabType
        {
            get
            {
                return _TabType;
            }
            set
            {
                OnTabTypeChanging(value);
                ReportPropertyChanging("TabType");
                _TabType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TabType");
                OnTabTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _TabType;
        partial void OnTabTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTabTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TabOrder
        {
            get
            {
                return _TabOrder;
            }
            set
            {
                OnTabOrderChanging(value);
                ReportPropertyChanging("TabOrder");
                _TabOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TabOrder");
                OnTabOrderChanged();
            }
        }
        private global::System.Int32 _TabOrder;
        partial void OnTabOrderChanging(global::System.Int32 value);
        partial void OnTabOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.String _DateCreated;
        partial void OnDateCreatedChanging(global::System.String value);
        partial void OnDateCreatedChanged();

        #endregion

    
    }

    #endregion

    
}
